name: Build opentelemetry cpp
on: [push]
jobs:
  windows_bazel:
    name: Bazel Windows
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        repository: 'open-telemetry/opentelemetry-cpp'

    - name: setup
      run: |
        ./ci/setup_windows_cmake.ps1
        ./ci/setup_windows_ci_environment.ps1
        ./ci/install_windows_bazelisk.ps1

    - name: run cmake 1
      run: |
        mkdir build && cd build && cmake ..
      
    - name: run cmake 2
      run: |
        cd build 
        cmake --build . --target all

    - name: run cmake 3
      run: |
        cd build 
        cmake --install . --config Release --prefix ${env.working-directory}/build/install

    - run: Compress-Archive -Path ${env.working-directory}/build -DestinationPath build.zip 
      shell: powershell

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: build.zip
        path: build.zip
        retention-days: 5
  # Build:
  #   runs-on: windows-latest
  #   steps:
  #     - run: git clone https://github.com/open-telemetry/opentelemetry-cpp.git
  #     - run: .\ci\setup_windows_ci_environment.ps1
  #       working-directory: opentelemetry-cpp
  #       shell: powershell
  #     - run: .\ci\setup_windows_cmake.ps1
  #       working-directory: opentelemetry-cpp
  #       shell: powershell
  #     - run: .\ci\install_windows_bazelisk.ps1
  #       working-directory: opentelemetry-cpp
  #       shell: powershell
  #     - run: .\ci\install_windows_protobuf.ps1
  #       working-directory: opentelemetry-cpp
  #       shell: powershell
  #     - run: .\ci\do_ci.ps1 bazel.build
  #       working-directory: opentelemetry-cpp
  #       shell: powershell