name: Build opentelemetry cpp
on: [push]
jobs:
  windows_bazel:
    name: Bazel Windows
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        repository: 'open-telemetry/opentelemetry-cpp'
#        ref: ''

    - name: setup
      run: ./ci/install_windows_bazelisk.ps1
    - name: run tests
      run: ./ci/do_ci.ps1 bazel.build

  # Build:
  #   runs-on: windows-latest
  #   steps:
  #     - run: git clone https://github.com/open-telemetry/opentelemetry-cpp.git
  #     - run: .\ci\setup_windows_ci_environment.ps1
  #       working-directory: opentelemetry-cpp
  #       shell: powershell
  #     - run: .\ci\setup_windows_cmake.ps1
  #       working-directory: opentelemetry-cpp
  #       shell: powershell
  #     - run: .\ci\install_windows_bazelisk.ps1
  #       working-directory: opentelemetry-cpp
  #       shell: powershell
  #     - run: .\ci\install_windows_protobuf.ps1
  #       working-directory: opentelemetry-cpp
  #       shell: powershell
  #     - run: .\ci\do_ci.ps1 bazel.build
  #       working-directory: opentelemetry-cpp
  #       shell: powershell